name: My First Workflow For RG Creation
on: [push]
  # push:
  #   branches:
  #     - main
  #     - feature/*
  
jobs:
  Terraform-Init:
    name: Terraform Init
    runs-on: my-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Azure Login 
      uses: Azure/login@v2.3.0
      with:
        creds: ${{ secrets.MYAZURECREDENTIALS }}
      
    - name: Terraform init
      run: terraform init
      working-directory: Parent_Module/Dev

  Terraform-Plan:
    name: Terraform Plan
    runs-on: my-runner
    needs: Terraform-Init
    steps:
    - name: Azure Login 
      uses: Azure/login@v2.3.0
      with:
        creds: ${{ secrets.MYAZURECREDENTIALS }}
      
    - name: Terraform init
      run: terraform init
      working-directory: Parent_Module/Dev
      
    - name: Terraform Plan
      run: terraform plan
      working-directory: Parent_Module/Dev
  
  Terraform-Apply:
    name: Terraform-Apply
    runs-on: my-runner
    needs: Terraform-Plan
    environment: erkumarsunil5786
    steps:
    - name: Azure Login 
      uses: Azure/login@v2.3.0
      with:
        creds: ${{ secrets.MYAZURECREDENTIALS }}
      
    - name: Terraform init
      run: terraform init
      working-directory: Parent_Module/Dev
      
    - name: Terraform Apply
      run: terraform apply --auto-approve
      working-directory: Parent_Module/Dev    
    
   
      
      
      
    
 

