name: My First Workflow For RG Creation
on: [push]
  # push:
  #   branches:
  #     - main
  #     - feature/*
  
jobs:
  Terraform-Init:
    name: Terraform Init
    runs-on: my-runner
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
     
    - name: HashiCorp-Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.11.4
      
    - name: Azure Login 
      uses: Azure/login@v2.3.0
      with:
        creds: ${{ secrets.MYAZURECREDENTIALS }}
      
    - name: Terraform init/plan
      run: terraform init
      working-directory: Parent_Module/Dev

  Code-Scaning:
    name: Security Scanning
    runs-on: my-runner
    needs: Terraform-Init
    steps:
    - name: TFlinit Setup
      run: |
       curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    - name: Run tflint for code quality
      run: tflint
      working-directory: Parent_Module/Dev
    
    - name: Install tfsec For Security
      run: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

    - name: Run tfsec for security scan
      run: tfsec .
      working-directory: Parent_Module/Dev
      
      
      
    
 

